/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */
 
#ifndef MC_LIMITS_H
#define	MC_LIMITS_H

#define MC_OVER_CURRENT_PEAK_EVENT_LEVEL    (44.0) // Amperes
#define MC_OVER_CURRENT_AVG_EVENT_LEVEL     (10.0) // Amperes
#define MC_OVER_TEMPERATURE_EVENT_LEVEL     (60.0) // Celsius Degrees
#define MC_OVER_TEMPERATURE_RESTORE_LEVEL   (50.0) // Celsius Degrees
#define MC_OVER_VOLTAGE_EVENT_LEVEL         (50.0) // Volts
#define MC_OVER_VOLTAGE_RESTORE_LEVEL       (49.0) // Volts
#define MC_UNDER_VOLTAGE_RESTORE_LEVEL      (7.0)  // Volts
#define MC_UNDER_VOLTAGE_EVENT_LEVEL        (6.0)  // Volts

#endif	/* MC_LIMITS_H */

