#include <avr/io.h>
#include "evsys.h"

void Evsys_Init(void)
{
    EVSYS.CHANNEL1 = EVSYS_CHANNEL_TCE0_OVF_gc;
    EVSYS.USERADC0START = EVSYS_USER_CHANNEL1_gc;
    
    EVSYS.USEREVSYSEVOUTA = EVSYS_USER_CHANNEL1_gc;
    PORTMUX.EVSYSROUTEA = PORTMUX_EVOUTA_ALT1_gc;

    EVSYS.CHANNEL0 = EVSYS_CHANNEL_AC1_OUT_gc;
    EVSYS.USERWEXA = EVSYS_USER_CHANNEL0_gc;
}
